"""
Assessment & Learning Report Engine
Generates multi-question diagnostic quizzes, evaluates answers, and constructs editorial learning reports using LLM.
"""

from typing import List, Dict, Any
from app.services.llm_service import LLMService

class AssessmentEngineService:
    def __init__(self, llm_service: LLMService):
        self.llm_service = llm_service
        self.fallback_questions = [
            {
                "id": "q1",
                "concept": "Foundational Concept",
                "prompt": "What happens if potential difference across a closed circuit drops to zero?",
                "options": {
                    "A": "Current increases drastically",
                    "B": "Electrons continue moving in a steady direction",
                    "C": "Current drops to zero because there is no electric driving force",
                    "D": "Resistance becomes infinite"
                },
                "correct_option": "C",
                "explanation": "Voltage is the driving potential; without ΔV, no net directional drift occurs."
            },
            {
                "id": "q2",
                "concept": "Resistance",
                "prompt": "How does increasing the thickness (cross-sectional area) of a copper wire affect its resistance?",
                "options": {
                    "A": "Resistance increases",
                    "B": "Resistance decreases",
                    "C": "Resistance remains unaffected",
                    "D": "Voltage drops to zero"
                },
                "correct_option": "B",
                "explanation": "A wider cross-sectional area provides more conduction pathways, reducing resistance."
            }
        ]

    async def generate_assessment(self, topic: str = "Ohm's Law") -> Dict[str, Any]:
        """
        Returns full diagnostic assessment with concept verification questions generated by LLM.
        """
        if not self.llm_service.is_configured():
            return {
                "total_questions": len(self.fallback_questions),
                "questions": self.fallback_questions,
                "passing_threshold_pct": 75
            }
            
        prompt = f"""
        Generate an 8-question multiple-choice quiz about {topic} to evaluate a student's mastery.
        Return EXACTLY this JSON schema:
        {{
            "total_questions": 8,
            "passing_threshold_pct": 75,
            "questions": [
                {{
                    "id": "q1",
                    "concept": "string (the sub-concept being tested)",
                    "prompt": "string (the question text)",
                    "options": {{"A": "string", "B": "string", "C": "string", "D": "string"}},
                    "correct_option": "A|B|C|D",
                    "explanation": "string (why the correct answer is right)"
                }}
            ]
        }}
        DO NOT use markdown blocks.
        """
        
        try:
            import google.generativeai as genai
            response = self.llm_service.model.generate_content(
                prompt,
                generation_config=genai.types.GenerationConfig(
                    response_mime_type="application/json"
                )
            )
            import json
            data = json.loads(response.text)
            return data
        except Exception as e:
            return {
                "total_questions": len(self.fallback_questions),
                "questions": self.fallback_questions,
                "passing_threshold_pct": 75
            }

    async def grade_assessment(self, student_answers: Dict[str, str], quiz_data: Dict[str, Any]) -> Dict[str, Any]:
        """
        Evaluates submitted quiz answers, determines mastery profile, and builds learning report.
        """
        questions = quiz_data.get("questions", self.fallback_questions)
        correct_count = 0
        breakdown = []
        needs_practice = set()
        strong_areas = set()

        for q in questions:
            qid = q["id"]
            user_choice = student_answers.get(qid, "").upper()
            is_correct = (user_choice == q["correct_option"])
            
            if is_correct:
                correct_count += 1
                strong_areas.add(q["concept"])
            else:
                needs_practice.add(q["concept"])
                
            breakdown.append({
                "question_id": qid,
                "concept": q["concept"],
                "student_choice": user_choice,
                "correct_option": q["correct_option"],
                "is_correct": is_correct
            })

        total = len(questions)
        score_pct = int((correct_count / total) * 100) if total > 0 else 0

        # Optional LLM report generation
        teacher_obs = f"You answered {correct_count} out of {total} correctly."
        if score_pct >= 75:
            teacher_obs += " Excellent work. You demonstrate strong understanding."
        else:
            teacher_obs += " You have some areas to review."

        return {
            "score_pct": score_pct,
            "correct_count": correct_count,
            "total_questions": total,
            "strong_areas": list(strong_areas),
            "needs_practice": list(needs_practice),
            "teacher_observation": teacher_obs,
            "recommended_action": "Review incorrect concepts" if score_pct < 75 else "Proceed to next module",
            "next_learning_step": "Proceed to next topic"
        }
